// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnJcy62h2Z3QIigF9NsgkOsIz3eWWSLe0',
    appId: '1:92717074049:android:000d0e6561ee3153eeef80',
    messagingSenderId: '92717074049',
    projectId: 'turndate-66502',
    storageBucket: 'turndate-66502.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2kdrkgvo_eTqwllPhXiy6IqOq7pYhYLs',
    appId: '1:92717074049:ios:8b740b09ed90c752eeef80',
    messagingSenderId: '92717074049',
    projectId: 'turndate-66502',
    storageBucket: 'turndate-66502.appspot.com',
    androidClientId: '92717074049-hsiae6t7budclifsu86knijqvsrhib5r.apps.googleusercontent.com',
    iosClientId: '92717074049-s9jo0du0u49cti9gnfqd9e4vb99lu6ti.apps.googleusercontent.com',
    iosBundleId: 'com.example.turndate',
  );

}